In [2]:
import numpy as np
print("Numpy Version:", np.__version__)

Numpy Version: 1.26.4


In [5]:
# Creating 1D, 2D, and 3D arrays
arr1 = np.array([1, 2, 3, 4, 5]) # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array

print("1D Array:", arr1)
print("2D Array:", arr2)
print("3D Array:", arr3)

print("Shape of arr2:", arr3.shape)
print("Size of arr2:", arr3.size)
print("Data type of arr2:", arr2.dtype)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of arr2: (2, 2, 2)
Size of arr2: 8
Data type of arr2: int64


In [12]:
# Special arrays
zeroes = np.zeros((3, 3))
ones = np.ones((2, 3))
identity = np.eye(4)
random_arr = np.random.rand(3, 3)

print("Zeroes:\n", zeroes)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)
print("Random Matrix:\n", random_arr)

Zeroes:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Matrix:
 [[0.09066492 0.35344788 0.25078054]
 [0.61637809 0.04967215 0.17152175]
 [0.76220337 0.03698245 0.29705918]]


In [15]:
# Accessing elements using indices - 1D Array
print(arr1)
print("First element:", arr1[0])
print("Last element:", arr1[-1])

# Accessing elements using indices - 2D Array
print(arr2)
print("Element at (1,1):", arr2[1,1])
print("Element at (2,0):", arr2[1,0])

# Accessing elements using indices - 3D Array
print(arr3)
print("Element at (1,1):", arr3[0, 1, 1])
print("Element at (2,0):", arr3[0, 1, 0])


[1 2 3 4 5]
First element: 1
Last element: 5
[[1 2 3]
 [4 5 6]]
Element at (1,1): 5
Element at (2,0): 4
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Element at (1,1): 4
Element at (2,0): 3


In [17]:
# Slicing
print(arr1[1:5])
print(arr1[::2])

[2 3 4 5]
[1 3 5]


In [24]:
print(arr3[1:3, 0:2])

[[[5 6]
  [7 8]]]


In [27]:
print(arr2[[1], [1]])

[5]


In [30]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
scalar = 10
result = arr + scalar

print("Original Array:", arr)
print("After Broadcasting:", result)

Original Array: [[1 2 3]
 [4 5 6]]
After Broadcasting: [[11 12 13]
 [14 15 16]]


In [ ]:
A = np.array([[2,3], [4,5]])
B = np.array([[1, 2], [3,4]])

C = np.dot(A, B)


[[11 16]
 [19 28]]


In [36]:
A_T = A.T
print(A_T)

[[2 4]
 [3 5]]


In [38]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.5  1.5]
 [ 2.  -1. ]]


In [39]:
eig_vals, eig_vecs = np.linalg.eig(A)
print(eig_vals)

[-0.27491722  7.27491722]
