In [2]:
from roboticstoolbox import *
from spatialmath.base import *
from spatialmath import *
import numpy as np
import scipy as sc

# Task 1

In [3]:
def rotation_xyx(a: float, b: float, c:float) -> np.ndarray:
    a, b, c = np.radians(a), np.radians(b), np.radians(c)
    return rotx(a) @ roty(b) @ rotx(c)

In [4]:
rotation_xyx(1.57, 1.57, 1.57)

array([[ 9.99624598e-01,  7.50663571e-04,  2.73879549e-02],
       [ 7.50663571e-04,  9.98498955e-01, -5.47656284e-02],
       [-2.73879549e-02,  5.47656284e-02,  9.98123552e-01]])

In [5]:
r = rotx(np.radians(45)) @ roty(np.radians(45)) @ rotx(np.radians(45)) @ [1, 1, 1]
r.round(3)

array([ 1.707, -0.207,  0.207])

In [6]:
a, b, c = -45, -45, -45
r = rotx(np.radians(a)) @ roty(np.radians(b)) @ rotx(np.radians(c)) @ [1, 1, 1]
r.round(3)

array([ 0.707,  1.5  , -0.5  ])

# Task 2

In [62]:
point = np.array([1, 1, 1])
a = np.array([0, 0, 1])   # Initial z-axis
o = np.array([1, 0, 0])   # Target x-axis# Target 45-degree in xy-plane
np.linalg.det(oa2r(o, a))

1.0

In [63]:
oa2r(o, a) @ point

array([ 1., -1.,  1.])

In [9]:
np.cross([1, 1, 1], [1, 1, 1])

array([0, 0, 0])

# Task 3

In [10]:
r = angvec2r(np.radians(45), [0, 1, 0]) @ [1, 1, 1]
r.round(3)

array([1.414, 1.   , 0.   ])

# Task 4

In [11]:
R = angvec2r(np.radians(-90), [1, 0, 1])
UnitQuaternion(R)

 0.7071 << -0.5000,  0.0000, -0.5000 >>


In [12]:
(UnitQuaternion(R) * [1, 1, 1]).round(3)

array([1.707, 0.   , 0.293])

In [13]:
(R @ [1, 1, 1]).round(3)

array([1.707, 0.   , 0.293])

In [14]:
theta, v = tr2angvec(R)

In [15]:
theta, v

(1.5707963267948961, array([-0.70710678,  0.        , -0.70710678]))

# Task 5

In [16]:
R = rotx(0.3)


In [17]:
L = sc.linalg.logm(R)
L.round(1)

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.3],
       [ 0. ,  0.3, -0. ]])

In [18]:
vex(L)  # skew sym to vector

array([0.3, 0. , 0. ])

In [19]:
R

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.95533649, -0.29552021],
       [ 0.        ,  0.29552021,  0.95533649]])

In [20]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 0, 1])

In [21]:
np.cross(v1, v2)

array([ 2,  2, -2])

In [22]:
vex(skew(v1)*v2)

array([0.5, 2. , 1.5])

In [23]:
skew([1, 2 , 3])

array([[ 0, -3,  2],
       [ 3,  0, -1],
       [-2,  1,  0]])

In [24]:
a = sc.linalg.logm(skew([1, 2, 3]))

In [25]:
a

array([[ -1.3966583 ,  -6.69181286,  -7.30893494],
       [ -4.172935  ,  -9.5452192 , -16.71693477],
       [ -8.98818685, -15.87730882, -23.12615403]])

In [26]:
# sc.linalg.expm(a)

In [27]:
sc.linalg.expm(L).round(1)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.3],
       [ 0. ,  0.3,  1. ]])

In [28]:
R = rotx(0.3)

In [29]:
R.round(1)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.3],
       [ 0. ,  0.3,  1. ]])

In [30]:
R = sc.linalg.expm(0.3 * skew([1, 0, 0]))

In [34]:
(R @ [1, 1, 1]).round(1)

array([1. , 0.7, 1.3])

In [40]:
A = skew([0, 1, 0])
vex(A)

array([0., 1., 0.])

In [38]:
sc.linalg.expm(np.radians(90) * A) @ [1, 1, 1]

array([ 1.,  1., -1.])

In [41]:
R = rotx(np.radians(90))
R

array([[ 1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  6.123234e-17, -1.000000e+00],
       [ 0.000000e+00,  1.000000e+00,  6.123234e-17]])

In [46]:
skew(vex(R))

array([[ 0., -0.,  0.],
       [ 0.,  0., -1.],
       [-0.,  1.,  0.]])

In [48]:
sc.linalg.expm(np.radians(90) * skew(vex(R))) @ [1, 1, 1]

array([ 1., -1.,  1.])

# Verification

In [60]:
angle = 45
array = [1, 0, 0]

In [61]:
r = angvec2r(np.radians(angle), array) @ [1, 1, 1]
r.round(3)

array([1.   , 0.   , 1.414])