In [17]:
from roboticstoolbox import *
from spatialmath.base import *
from spatialmath import *
import numpy as np
import scipy as sc

# Task 1

In [18]:
def rotation_xyx(a: float, b: float, c:float) -> np.ndarray:
    a, b, c = np.radians(a), np.radians(b), np.radians(c)
    return rotx(a) @ roty(b) @ rotx(c)

In [19]:
rotation_xyx(1.57, 1.57, 1.57)

array([[ 9.99624598e-01,  7.50663571e-04,  2.73879549e-02],
       [ 7.50663571e-04,  9.98498955e-01, -5.47656284e-02],
       [-2.73879549e-02,  5.47656284e-02,  9.98123552e-01]])

# Task 2

In [49]:
point = np.array([1, 1, 1])
a = np.array([1, 0, 0])
o = np.array([0, 1, 0])

In [50]:
oa2r(o, a) @ point

array([ 1.,  1., -1.])

In [ ]:
point = np.array([1, 1, 1])
a = np.array([1, 0, 0])
o = np.array([-1, 0, 0])
oa2r(o, a) @ point

ValueError: zero norm vector

# Task 3

In [22]:
angvec2r(np.radians(90), [1, 0, 0]) @ [1, 1, 1]

array([ 1., -1.,  1.])

# Task 4

In [23]:
R = rpy2r(0, 0, 0)
R

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
UnitQuaternion(R)

 1.0000 <<  0.0000,  0.0000,  0.0000 >>


In [25]:
theta, v = tr2angvec(R)

In [26]:
theta, v

(0, array([0, 0, 0]))

# Task 5

In [27]:
R = rotx(0.3)


In [33]:
L = sc.linalg.logm(R)
L.round(1)

array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. , -0.3],
       [ 0. ,  0.3, -0. ]])

In [ ]:
vex(L)  # skew sym to vector

array([0.3, 0. , 0. ])

In [41]:
R

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.95533649, -0.29552021],
       [ 0.        ,  0.29552021,  0.95533649]])

In [45]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 0, 1])

In [46]:
np.cross(v1, v2)

array([ 2,  2, -2])

In [48]:
vex(skew(v1)*v2)

array([0.5, 2. , 1.5])

In [55]:
skew([1, 2 , 3])

array([[ 0, -3,  2],
       [ 3,  0, -1],
       [-2,  1,  0]])

In [59]:
a = sc.linalg.logm(skew([1, 2, 3]))

In [60]:
a

array([[ -1.3966583 ,  -6.69181286,  -7.30893494],
       [ -4.172935  ,  -9.5452192 , -16.71693477],
       [ -8.98818685, -15.87730882, -23.12615403]])

In [ ]:
# sc.linalg.expm(a)

LinAlgError: The input array must be at least two-dimensional

In [62]:
sc.linalg.expm(L).round(1)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.3],
       [ 0. ,  0.3,  1. ]])

In [63]:
R = rotx(0.3)

In [65]:
R.round(1)

array([[ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -0.3],
       [ 0. ,  0.3,  1. ]])

In [68]:
R = sc.linalg.expm(0.3 * skew([1, 0, 0]))

In [72]:
(R @ [1, 1, 1]).round(1)

array([1. , 0.7, 1.3])